Repository nc-dtan/crispy-adventure, pull requests merged in 2019-01, with the labels that each got.

#7 Feature/psrm db
  .gitignore
  psrmDB.py
Labels: feature

#16 Feature/retrieve acl
  psrmDB.py
Labels: feature

#17 Cast some columns to int/float instead of object to save 33% memory
  psrmDB.py
Labels: enhancement

#20 Cleanup for data input.
  default_paths.py
  psrm_ci_ft_base.py
Labels: refactor

#24 len of an object return len of the DataFrame
  data.py
Labels: enhancement

#27 Fix/convert amount to decimal
  afregning.py
  psrm_utils.py
  udligning.py
  udtraek.py
  underretning.py
  utils.py
Labels: enhancement

#29 Feature/bi 2034 xml handler
  udligning/afregning.py
  udligning/enums/__init__.py
  udligning/enums/aktivitettype.py
  udligning/enums/artkode.py
  udligning/enums/kundetype.py
  udligning/enums/typekategori.py
  udligning/enums/typekode.py
Labels: feature

#28 Feature/parallel computing in class
  requirements.txt
  udtraek.py
Labels: enhancement

#30 Add XML tools to requirements.txt
  requirements.txt
Labels: bug

#33 Feature/fix afregning module
  .gitignore
  afregningService.py
  udligning/__init__.py
  udligning/afregning.py
Labels: enhancement

#34 Feature/organize in packages
  makefile
  psrm/__init__.py
  psrm/datamodel/__init__.py
  psrm/datamodel/afregning.py
  psrm/datamodel/data.py
  psrm/datamodel/udligning.py
  psrm/datamodel/udtraek.py
  psrm/datamodel/underretning.py
  psrm/enums/__init__.py
  psrm/enums/aktivitettype.py
  psrm/enums/artkode.py
  psrm/enums/kundetype.py
  psrm/enums/typekategori.py
  psrm/enums/typekode.py
  psrm/korrektion/__init__.py
  psrm/korrektion/afregning.py
  psrm/psrmDB.py
  psrm/psrm_ci_ft_base.py
  psrm/reports/report.py
  psrm/services/__init__.py
  psrm/services/afregningService.py
  psrm/utils/__init__.py
  psrm/utils/psrm_utils.py
  psrm/utils/utils.py
  psrm/validator.py
  setup.py
Labels: enhancement

#40 Feature/unit test
  .travis.yml
  psrm/psrmDB.py
  psrm/tests/test_enums.py
  test_requirements.txt
Labels: feature

#48 Extracting data with query is 2x faster than indexing
  psrm/psrm_ci_ft_base.py
Labels: enhancement

#49 Find a target sum in combinations of a list of numbers
  psrm/utils/number_util.py
Labels: feature

#41 Feature/xml service
  psrm/enums/aktivitettype.py
  psrm/enums/typekode.py
  psrm/korrektion/afregning.py
  psrm/services/afregningService.py
  psrm/tests/test_enums.py
  psrm/tests/test_language_util.py
  psrm/utils/language_util.py
Labels: enhancement

#50 Add method to check for samtidighed
  psrm/datamodel/afregning.py
Labels: feature
